import type { Metadata } from 'next';
import LegalPage, { legal } from '@/components/layout/LegalPage';

export const metadata: Metadata = {
  title: 'Terms of Service — Tribhuban Concepts',
  description: 'The rules and conditions for using the Tribhuban Concepts website and services, governed by Indian law.',
  robots: { index: true, follow: true },
};

export const revalidate = false;

export default function TermsPage() {
  const sections = [
    {
      id: 'acceptance', number: '1', title: 'Acceptance of Terms',
      content: (
        <>
          <p className={legal.p}>By accessing or using <strong>tribhubanconcepts.com</strong> (the &ldquo;Website&rdquo;), operated by Tribhuban Concepts (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;), you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to all of these Terms, you must not use the Website.</p>
          <p className={legal.p}>We may update these Terms from time to time. Continued use of the Website after any changes constitutes acceptance of the revised Terms. We will indicate the date of the most recent revision at the top of this page.</p>
        </>
      ),
    },
    {
      id: 'permitted-use', number: '2', title: 'Permitted Use',
      content: (
        <>
          <p className={legal.p}>You may use the Website for lawful purposes only. You agree that you will not:</p>
          <ul className={legal.ul}>
            <li className={legal.li}>Use the Website in any way that violates applicable Indian or international laws or regulations.</li>
            <li className={legal.li}>Submit false, misleading, or fraudulent information through any form on the Website.</li>
            <li className={legal.li}>Attempt to gain unauthorised access to any part of the Website, its servers, or any related systems or networks.</li>
            <li className={legal.li}>Use automated tools (bots, scrapers, crawlers) to collect data in a manner that adversely affects performance or circumvents rate limits — except for search-engine crawlers explicitly permitted in our <code className={legal.code}>robots.txt</code>.</li>
            <li className={legal.li}>Transmit any material that is harmful, offensive, defamatory, or infringes any intellectual-property rights.</li>
            <li className={legal.li}>Attempt to reverse-engineer, decompile, or disassemble any software or underlying technology of the Website.</li>
          </ul>
          <p className={legal.p}>We reserve the right to refuse service, terminate access, or take legal action against anyone who violates these Terms.</p>
        </>
      ),
    },
    {
      id: 'intellectual-property', number: '3', title: 'Intellectual Property',
      content: (
        <>
          <p className={legal.p}>All content on this Website — including text, articles, graphics, logos, icons, images, audio clips, and software — is the exclusive property of Tribhuban Concepts or its content suppliers and is protected by Indian copyright law and international copyright treaties.</p>
          <p className={legal.p}>You may view, download, and print content from this Website for your personal, non-commercial use only, provided you do not modify the content and retain all copyright and proprietary notices.</p>
          <p className={legal.p}>No content may be reproduced, distributed, publicly displayed, or used to create derivative works without our prior written permission. The Tribhuban Concepts name, logo, and all associated marks are trademarks and may not be used without explicit written authorisation.</p>
        </>
      ),
    },
    {
      id: 'disclaimers', number: '4', title: 'Disclaimers',
      content: (
        <>
          <p className={legal.p}>The Website and its content are provided on an <strong>&ldquo;as is&rdquo; and &ldquo;as available&rdquo;</strong> basis without warranties of any kind, whether express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement.</p>
          <p className={legal.p}>The solar savings estimates generated by our Solar Calculator are <strong>indicative only</strong>. Actual savings will depend on site-specific factors including roof orientation, shading, local grid tariffs, and system performance. Estimates do not constitute a quote, guarantee, or engineering assessment. You should obtain a professional site survey before making financial decisions.</p>
          <p className={legal.p}>We do not warrant that the Website will be uninterrupted, error-free, free of viruses, or that defects will be corrected. We reserve the right to modify, suspend, or discontinue any part of the Website at any time without notice.</p>
        </>
      ),
    },
    {
      id: 'liability', number: '5', title: 'Limitation of Liability',
      content: (
        <>
          <p className={legal.p}>To the fullest extent permitted by applicable Indian law, Tribhuban Concepts shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or in connection with your use of the Website or these Terms, even if we have been advised of the possibility of such damages.</p>
          <p className={legal.p}>Our total aggregate liability to you for any claim arising from or related to the Website shall not exceed the amount you paid, if any, to access the Website or services in the twelve (12) months preceding the claim.</p>
          <p className={legal.p}>Some jurisdictions do not allow the exclusion or limitation of certain warranties or liabilities; in such jurisdictions, our liability is limited to the greatest extent permitted by law.</p>
        </>
      ),
    },
    {
      id: 'governing-law', number: '6', title: 'Governing Law and Contact',
      content: (
        <>
          <p className={legal.p}>These Terms shall be governed by and construed in accordance with the laws of <strong>India</strong>, without regard to conflict-of-law principles. Any dispute arising from these Terms or your use of the Website shall be subject to the exclusive jurisdiction of the courts located in India.</p>
          <p className={legal.p}>If you have any questions about these Terms or wish to seek permission for uses not covered above, please contact us:</p>
          <address className={legal.address}>
            <p><strong>Tribhuban Concepts — Legal</strong></p>
            <p>Email: <a href="mailto:hello@tribhubanconcepts.com" className={legal.a}>hello@tribhubanconcepts.com</a></p>
            <p>India</p>
          </address>
        </>
      ),
    },
  ];

  return (
    <LegalPage
      title="Terms of Service"
      lastUpdated="June 2025"
      description="The rules and conditions for using the Tribhuban Concepts website and services, governed by Indian law."
      sections={sections}
    />
  );
}
